@echo off
echo Killing Node processes...
taskkill /F /IM node.exe >nul 2>&1

echo Deleting .next cache...
rmdir /s /q .next >nul 2>&1

echo Generating Prisma Client...
call npx prisma generate

echo Starting Next.js...
npx next dev -p 3014
